source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.8'

gem 'active_model_serializers', '~> 0.10.13'
gem 'ancestry'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'cats_core', '~> 1.5.25'
gem 'groupdate', '~> 5.2.2'
gem 'jwt', '~> 2.3.0'
gem 'pg', '>= 1.5.0'
gem 'puma', '~> 5.5.2'
gem 'pundit', '~> 2.1.0'
gem 'rack-cors'
gem 'rails', '~> 7.0.1'
gem 'ransack', '~> 2.5.0'
gem 'rolify', '~> 6.0.0'
gem 'sablon'

group :development, :test do
  gem 'bullet'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'ffaker'
  gem 'panolint'
  gem 'pronto'
  gem 'pronto-rubocop', require: false
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :test do
  gem 'database_cleaner-active_record'
  gem 'shoulda-matchers'
  gem 'simplecov'
  gem 'timecop'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data'
